[tool.poetry]
name = "LuCaptcha"
version = "0.1.0"
description = ""
authors = ["absucc", "captcha"]

[tool.poetry.dependencies]
python = "^3.8"
captcha = "^0.3"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
